version: "3.8"
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        hostname: mongodb
        volumes:
            - ./etc/mongod.conf:/etc/mongod.conf
            - ./mongodb/data/db/:/data/db/
            - ./mongodb/data/log/:/var/log/mongodb/
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        ports:
            - "27017:27017"
        logging:
            options:
                max-size: 1g        
        command: ["-f", "/etc/mongod.conf"]
        networks:
            vpcbr:
                ipv4_address: 10.5.0.5
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '0.1'
                    memory: 200M

    webserver:
        image: raychorn/microservices-framework:2.0.1
        container_name: vyperapi
        restart: unless-stopped
        volumes:
            - ./django/logs/:/var/log/django/
        ports:
            - "9000:9000"
        depends_on:
            - mongodb
        env_file:
            - .env
        environment:
            WAIT_HOSTS: mongodb:27017
        #entrypoint:
        #    - /bin/bash
        tty: true
        stdin_open: true
        command: ["/workspaces/microservices-framework/runserver.sh"]
        deploy:
            resources:
                limits:
                    cpus: '0.9'
                    memory: 1000M
        networks:
            vpcbr:
                ipv4_address: 10.5.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1