
GET http://127.0.0.1:8088/rest/services/__dir__/ HTTP/1.1

###

GET http://127.0.0.1:8088/rest/services/hello-world/1/2/3/4/5/6/7/8/9/10/?a=1&b=2&c=3&d=4 HTTP/1.1

###

GET http://127.0.0.1:8088/rest/services/hello-world/2/3/4/5/?a=1&b=2&c=3&d=4 HTTP/1.1

###  The following should fail with a 404.

POST http://127.0.0.1:8088/rest/services/hello-world/?a=1&b=2&c=3&d=4 HTTP/1.1
content-type: application/json

{
    "args": [1,2,3,4,5,6],
    "name1": "one",
    "name2": "two",
    "name3": "three",
    "name4": "four"
}

###

GET http://127.0.0.1:8088/rest/services/bar-none/ HTTP/1.1

###

GET http://127.0.0.1:8088/rest/services/hello-world/?a=1&b=2&c=3&d=4 HTTP/1.1

###

POST http://127.0.0.1:8088/rest/services/sample-one/1/2/3/4/5/6/7/8/9/10/?a=1&b=2&c=3&d=4 HTTP/1.1
content-type: application/json

{
    "args": [1,2,3,4,5,6],
    "name1": "one",
    "name2": "two",
    "name3": "three",
    "name4": "four"
}

###

PUT http://127.0.0.1:8088/rest/services/sample-one2/1/2/3/4/5/6/7/8/9/10/?a=1&b=2&c=3&d=4 HTTP/1.1
content-type: application/json

{
    "args": [1,2,3,4,5,7],
    "name1": "one",
    "name2": "two",
    "name3": "three",
    "name4": "fourty"
}

###

DELETE http://127.0.0.1:8088/rest/services/sample-one2a/1/2/3/4/5/6/7/8/9/10/?a=1&b=2&c=3&d=4 HTTP/1.1
content-type: application/json

{
    "args": [1,2,3,4,5,7],
    "name1": "one",
    "name2": "two",
    "name3": "three",
    "name4": "fourty"
}

###

DELETE http://127.0.0.1:8088/rest/services/sample-two/2/ HTTP/1.1
content-type: application/json

{
    "args": [1,2,3,4,5,6,7],
    "name1": "one",
    "name2": "two",
    "name3": "three",
    "name4": "four"
}

###  The following demo API Versioning.

GET http://127.0.0.1:8088/rest/services/module1/hello-world/1/2/3/4/5/6/7/8/9/10/?a=1&b=2&c=3&d=4 HTTP/1.1

###

GET http://127.0.0.1:8088/rest/services/hello-world/1/2/3/4/5/6/7/8/9/10/?a=1&b=2&c=3&d=4 HTTP/1.1

###

DELETE http://127.0.0.1:8088/rest/services/modules1/sample-one2a/1/2/3/4/5/6/7/8/9/10/?a=1&b=2&c=3&d=4 HTTP/1.1
content-type: application/json

{
    "args": [1,2,3,4,5,7],
    "name1": "one",
    "name2": "two",
    "name3": "three",
    "name4": "fourty",
    "__map__" : {
        "parm_1" : "p1",
        "parm_2" : "p2",
        "parm_3" : "p3",
        "parm_4" : "p4",
        "parm_5" : "p5",
        "parm_6" : "p6",
        "parm_7" : "p7",
        "parm_8" : "p8",
        "parm_9" : "p9",
        "parm_10" : "p10"
    }
}

### 

GET http://127.0.0.1:8088/rest/services/__dir__/ HTTP/1.1

###

POST http://127.0.0.1:8088/rest/services/sample-one/1/2/3/4/5/6/7/8/9/10/?a=1&b=2&c=3&d=4 HTTP/1.1
content-type: application/json

{
    "args": [1,2,3,4,5,6],
    "name1": "one",
    "name2": "two",
    "name3": "three",
    "name4": "four",
    "__map__" : {
        "parm_1" : "p1",
        "parm_2" : "p2",
        "parm_3" : "p3",
        "parm_4" : "p4",
        "parm_5" : "p5",
        "parm_6" : "p6",
        "parm_7" : "p7",
        "parm_8" : "p8",
        "parm_9" : "p9",
        "parm_10" : "p10"
    }
}

###

POST http://127.0.0.1:8088/rest/services/v1/sample-one/1/2/3/4/5/6/7/8/9/10/?a=1&b=2&c=3&d=4 HTTP/1.1
content-type: application/json

{
    "args": [1,2,3,4,5,6],
    "name1": "one",
    "name2": "two",
    "name3": "three",
    "name4": "four",
    "__map__" : {
        "parm_1" : "p1",
        "parm_2" : "p2",
        "parm_3" : "p3",
        "parm_4" : "p4",
        "parm_5" : "p5",
        "parm_6" : "p6",
        "parm_7" : "p7",
        "parm_8" : "p8",
        "parm_9" : "p9",
        "parm_10" : "p10"
    }
}
